version: "3.8"
services:
  app:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://berry:berry@db:5432/sod-db
      - PRISMA_SCHEMA_PATH=/app/prisma/schema.prisma
      - NEXTAUTH_URL=http://localhost:3000
      # Uncomment these when you have the environment variables set
      # - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      # - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      # - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      # - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./sod-t3:/app
      - /app/node_modules
      - ./sod-t3/prisma:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    networks:
      - app-network
    image: postgres:13
    environment:
      - POSTGRES_USER=berry
      - POSTGRES_PASSWORD=berry
      - POSTGRES_DB=sod-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U berry -d sod-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
